name: teamx
version: 2.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  url_launcher: ^6.1.5
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_ads_mediation: ^1.3.1
 
dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/

